# q(x, b) − Amenity(x), next(x, a), next(a, b), Shop(b)

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

PREFIX tuwt: <http://www.kr.tuwien.ac.at/myits/geoconcepts/terms#>
PREFIX tuwti: <http://www.kr.tuwien.ac.at/myits/geoconcepts/items#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX gml: <http://www.opengis.net/gml/>
PREFIX geo: <http://www.georss.org/georssl/>
PREFIX : <http://www.kr.tuwien.ac.at/myits/geoconcepts/items#>

SELECT ?xname ?bname 
WHERE { 
    ?x a tuwt:Amenity . 
    ?x tuwt:isLocatedNext ?a .
    ?a tuwt:isLocatedNext ?b .
    ?b a tuwt:Shop .

        
    ?x gml:featurename ?xname .
    ?b gml:featurename ?bname .
}
