# q4(x,y) <- Shop(x), next(x, u), Point(u), connected(u, v),
# connected(v, w), Point(w), next(y, w), Bank(y), hasOperator(y, z),
# BankSmallOp(z)

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

PREFIX tuwt: <http://www.kr.tuwien.ac.at/myits/geoconcepts/terms#>
PREFIX tuwti: <http://www.kr.tuwien.ac.at/myits/geoconcepts/items#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX gml: <http://www.opengis.net/gml/>
PREFIX geo: <http://www.georss.org/georssl/>
PREFIX : <http://www.kr.tuwien.ac.at/myits/geoconcepts/items#>

SELECT DISTINCT  ?x ?y
WHERE { 
     ?x a tuwt:Shop .
     ?x tuwt:isLocatedNext ?u .
     ?u a tuwt:Point .
     ?u tuwt:connected ?v .
     ?v tuwt:connected ?w .
     ?w a tuwt:Point .
     ?y tuwt:isLocatedNext ?w .
     ?y a tuwt:Bank .
     ?y tuwt:hasOperator ?z.
     ?z a tuwt:BankSmallOp .
}
